services:
  projetofinalweb:
    image: ${DOCKER_REGISTRY-}projetofinalweb
    build:
      context: .
      dockerfile: projetofinalweb/Dockerfile
    depends_on:
        - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_TCP_PORT=1433
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "1433:1433"